apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: {{ .Release.Name }}-helm-repo
spec:
  interval: 1m
  url: {{ .Values.helm.repo.url }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-helm-release
spec:
  interval: 5m
  chart:
    spec:
      chart: {{ .Values.helm.repo.chart.name }}
      version: {{ .Values.helm.repo.chart.version }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Release.Name }}-helm-repo