apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Release.Name }}-helm-repo-propagation-policy
spec:
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: HelmRepository
      name: {{ .Release.Name }}-helm-repo
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clusters }}
        - {{ . }}
        {{- end }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Release.Name }}-helm-release-propagation-policy
spec:
  resourceSelectors:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: {{ .Release.Name }}-helm-release
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clusters }}
        - {{ . }}
        {{- end }}