apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: default
  {{- if .Values.route.hostname.enabled }}
  hostnames:
  - {{ .Values.route.hostname.url }}
  {{- end }}
  rules:
  - matches:
    - path:
        value: {{ .Values.route.path }}
    backendRefs:
    - name: {{ .Values.route.backendRefs.name }}
      port: {{ .Values.route.backendRefs.port }}