apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Release.Name }}-route-propagation-policy
spec:
  resourceSelectors:
    - apiVersion: gateway.networking.k8s.io/v1beta1
      kind: HTTPRoute
      name: {{ .Release.Name }}-route
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.clusters }}
        - {{ . }}
        {{- end }}